#!/bin/bash
mkdir -p /Source/build64
cd /Source/build64
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu precise main" | tee /etc/apt/sources.list.d/mono-official.list
apt-get update
apt-get --assume-yes install pkg-config cmake build-essential mono-devel mono-runtime-sgen
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig
cp /usr/lib/libmono-2.0.a ../libmonosgen-2.0.a
cmake -DCMAKE_C_FLAGS="-m64" ..
make
mkbundle --static --keeptemp -o mcs.x86_64.bin -L /usr/lib/mono/4.5/ /usr/lib/mono/4.5/mcs.exe
patch temp.c ../mcs.c.patch
cc -o 'mcs.x86_64.bin' -Wall temp.c `pkg-config --cflags --libs mono-2`  temp.o

