#!/bin/bash
cp /Library/Frameworks/Mono.framework/Versions/Current/lib/libmonosgen-2.0.a ./
mkdir build
cd build
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/Library/Frameworks/Mono.framework/lib/pkgconfig
cmake -DCMAKE_OSX_ARCHITECTURES="i386;x86_64" ..
make
cd ..
docker pull ubuntu:12.04
docker pull erwinchang/ubuntu-12.04-32bit
docker run -i -v "${PWD}:/Source" ubuntu:12.04 /bin/bash -c "/Source/buildlinux64"
docker run -i -v "${PWD}:/Source" erwinchang/ubuntu-12.04-32bit /bin/bash -c "linux32 --32bit i386 /Source/buildlinux32"
