#!/bin/bash
# MonoKickstart Mcs Shell Script
# Written by Dean Ellis
# Based on Kick Shell Script by Ethan "flibitijibibo" Lee

# Move to script's directory
cd "`dirname "$0"`"

# Get the system architecture
UNAME=`uname`
ARCH=`uname -m`

# MonoKickstart picks the right libfolder, so just execute the right binary.
if [ "$UNAME" == "Darwin" ]; then
	./mcs.bin.osx "$@"
else
	if [ "$ARCH" == "x86_64" ]; then
		./mcs.bin.x86_64 "$@"
	else
		./mcs.bin.x86 "$@"
	fi
fi
